network.host: 0.0.0.0

index:
  analysis:
    analyzer:
      ik:
        alias:
        - ik_analyzer
        type: ik
      ik_max_word:
        type: ik
        use_smart: false
      ik_smart:
        type: ik
        use_smart: true

index.analysis.analyzer.default.type: ik
script.engine.groovy.inline.aggs: on
script.inline: on
script.indexed: on
